# Generated by Django 3.1.7 on 2021-05-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('idDenominación', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Denominacion')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoUva',
            fields=[
                ('idUva', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('idVino', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('denominacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.denominacion')),
                ('tiposUva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.tipouva')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='denominacion',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.pais'),
        ),
    ]
