# Generated by Django 3.1.7 on 2021-05-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denominacion',
            old_name='idDenominación',
            new_name='idDenominacion',
        ),
    ]
