# Generated by Django 3.2 on 2021-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210513_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField(verbose_name='Artist')),
                ('catalog_number', models.TextField(verbose_name='Catalog Number')),
                ('title', models.TextField(verbose_name='Title')),
                ('year', models.TextField(verbose_name='Year')),
                ('image', models.TextField(verbose_name='Image')),
            ],
            options={
                'ordering': ('catalog_number',),
            },
        ),
        migrations.RemoveField(
            model_name='vino',
            name='denominacion',
        ),
        migrations.RemoveField(
            model_name='vino',
            name='tiposUva',
        ),
        migrations.DeleteModel(
            name='Denominacion',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='TipoUva',
        ),
        migrations.DeleteModel(
            name='Vino',
        ),
    ]
