# Generated by Django 3.2 on 2021-06-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210612_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ('-year',)},
        ),
    ]
