# Generated by Django 3.2 on 2021-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_release_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasesDiscogs',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField(verbose_name='Artist')),
                ('catalog_number', models.TextField(
                    verbose_name='Catalog Number')),
                ('title', models.TextField(verbose_name='Title')),
                ('year', models.TextField(verbose_name='Year')),
                ('image', models.TextField(verbose_name='Image')),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.RenameModel(
            old_name='Release',
            new_name='ReleaseBeatport',
        ),
    ]
