# Generated by Django 3.2 on 2021-06-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210613_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReleaseBeatport',
            new_name='ReleasesBeatport',
        ),
    ]
